import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src/react'),
    },
  },
  test: {
    environment: 'happy-dom',
    // 其余 tests/*.test.js 使用 node:test，由 `node --test` 单独运行
    include: [
      'tests/compose-attach.test.js',
      'tests/web-embed-url.test.js',
      'tests/global-assistant.test.js',
      'tests/assistant-display-noise.test.js',
      'tests/chat-normalize.test.js',
      'tests/clarify-preview-resolve.test.js',
      'tests/tool-display.test.js',
      'tests/subagent-stream-merge.test.js',
      'tests/terminal-stream-merge.test.js',
      'tests/subagent-type-policy.test.js',
      'tests/subtask-result-display.test.js',
      'tests/subtask-modal-rows.test.js',
      'tests/subtask-modal-message-row.test.js',
      'tests/subagent-tool-display.test.js',
      'tests/transcript-persist.test.js',
      'tests/transcript-resume-anchor.test.js',
      'tests/workspace-api-scope.test.js',
      'tests/workspace-stream-preview.test.js',
      'tests/workspace-html-preview.test.js',
      'tests/tool-approval.test.js',
      'tests/plan-exec-ui.test.js',
      'tests/collab-sidebar-tools.test.js',
      'tests/plan-pipeline.test.js',
      'tests/plan-task-status.test.js',
      'tests/plan-from-api.test.js',
      'tests/collab-subtasks-from-api.test.js',
      'tests/collab-thread-ids.test.js',
      'tests/subtask-live-preview.test.js',
      'tests/proactive-work-process-live.test.js',
      'tests/proactive-session-messages.test.js',
      'tests/employee-current-task.test.js',
      'tests/plan-flowchart.test.js',
      'tests/plan-flowchart-render.test.js',
      'tests/app-workflow-canvas-json.test.js',
      'tests/app-run-form.test.js',
      'tests/app-run-controls.test.js',
      'tests/app-workflow-step-bridge.test.js',
      'tests/app-publish-check.test.js',
      'tests/app-api-call-example.test.js',
      'tests/agent-caps-display.test.js',
      'tests/evoflow-intro-prompt.test.js',
      'tests/exploring-activity-group.test.js',
      'tests/window-live-exploring-pieces.test.js',
      'tests/live-stream-path.test.js',
      'tests/live-stream-tail.test.js',
      'tests/client-perf.test.js',
      'tests/client-perf-scenarios.test.js',
      'tests/verify-perf-report.test.js',
      'tests/verify-perf-stress.test.js',
      'tests/post-search-read-tools.test.js',
      'tests/stream-turn-engine.test.js',
      'tests/openai-stream-turn.test.js',
      'tests/agui-turn-reducer.test.js',
      'tests/agui-display-segments-snapshot.test.js',
      'tests/content-blocks.test.js',
      'tests/use-thread-history-live.test.js',
      'tests/resolve-live-stream-activity.test.js',
      'tests/session-runtime-store.test.js',
      'tests/session-execution.test.js',
      'tests/session-list-pin.test.js',
      'tests/session-list-proactive-group.test.js',
      'tests/shell-running-preview.test.js',
      'tests/turn-text-isolation.test.js',
      'tests/ws-turn-slice.test.js',
      'tests/run-turn-gate.test.js',
      'tests/turn-strip-runtime.test.js',
      'tests/display-run-id.test.js',
      'tests/file-diff-util.test.js',
      'tests/file-edit-tool-fetch.test.js',
      'tests/stream-bump-scheduler.test.js',
      'tests/stream-bump-interval.test.js',
      'tests/markdown-stream-paint.test.js',
      'tests/sse-frame-batch.test.js',
      'tests/stream-display-tick.test.js',
      'tests/markdown-render-client.test.js',
      'tests/stream-resume-gate.test.js',
      'tests/stream-reattach-cooldown.test.js',
      'tests/session-reattach.test.js',
      'tests/context-usage.test.js',
      'tests/agent-trace-compaction.test.js',
      'tests/agent-avatar.test.js',
      'tests/agent-tags.test.js',
      'tests/message-row-stream-display.test.js',
      'tests/message-row-stream-layout.test.js',
      'tests/message-row-display-plan-path.test.js',
      'tests/message-row-streaming.test.js',
      'tests/message-row-timeline.test.js',
      'tests/turn-display-phase.test.js',
      'tests/turn-timing.test.js',
      'tests/message-row-reasoning-display.test.js',
      'tests/reasoning-display-text.test.js',
      'tests/activity-fold-visible-content.test.js',
      'tests/fold-induced-scroll-away.test.js',
      'tests/gateway-warm-latch.test.js',
      'tests/app-server-client.test.js',
      'tests/merge-assistant-stream-row.test.js',
      'tests/collapse-same-turn-assistants.test.js',
      'tests/session-debug-turn-groups.test.js',
      'tests/pick-session-row-title.test.js',
      'tests/chat-layout-bottom-dock.test.js',
      'tests/system-prompt-sections.test.js',
      'tests/reconcile-last-assistant-from-history.test.js',
      'tests/operations-render.test.js',
      'tests/obs-dashboard.test.tsx',
      'tests/obs-payload-parse.test.js',
      'tests/knowledge-map-tree.test.js',
      'tests/knowledge-map-diagram.test.js',
      'tests/knowledge-map-node-status.test.js',
      'tests/knowledge-map-xmind-layout.test.js',
      'tests/knowledge-vault.test.js',
      'tests/knowledge-graph-layout.test.js',
      'tests/knowledge-graph-explore.test.js',
      'tests/background-voice.test.js',
      'tests/voice-listen-control.test.js',
      'tests/voice-reply-speech.test.js',
      'tests/speech-client-queue.test.js',
      'tests/goal-closure-local.test.js',
      'tests/license-nav.test.js',
      'tests/developer-agents.test.js',
      'tests/task-summary-outputs.test.js',
      'tests/task-tree.test.js',
      'tests/ui-extension-manifest.test.js',
      'tests/markdown-document-view.test.js',
      'tests/decide-right-stage.test.js',
      'tests/platform-feedback.test.js',
      'tests/permission-tier.test.js',
      'tests/chat-host-route-toggle.test.js',
      'tests/shell-session-select-defer.test.js',
    ],
  },
})
